// paisesData.js
// Lista completa de países con código telefónico internacional
// Uso: import { PAISES_DATA } from './paisesData';

export const PAISES_DATA = [
  { nombre: "Afganistán", codigoTel: "+93" },
  { nombre: "Albania", codigoTel: "+355" },
  { nombre: "Alemania", codigoTel: "+49" },
  { nombre: "Andorra", codigoTel: "+376" },
  { nombre: "Angola", codigoTel: "+244" },
  { nombre: "Antigua y Barbuda", codigoTel: "+1-268" },
  { nombre: "Arabia Saudita", codigoTel: "+966" },
  { nombre: "Argelia", codigoTel: "+213" },
  { nombre: "Argentina", codigoTel: "+54" },
  { nombre: "Armenia", codigoTel: "+374" },
  { nombre: "Australia", codigoTel: "+61" },
  { nombre: "Austria", codigoTel: "+43" },
  { nombre: "Azerbaiyán", codigoTel: "+994" },
  { nombre: "Bahamas", codigoTel: "+1-242" },
  { nombre: "Bangladés", codigoTel: "+880" },
  { nombre: "Barbados", codigoTel: "+1-246" },
  { nombre: "Baréin", codigoTel: "+973" },
  { nombre: "Bélgica", codigoTel: "+32" },
  { nombre: "Belice", codigoTel: "+501" },
  { nombre: "Benín", codigoTel: "+229" },
  { nombre: "Bielorrusia", codigoTel: "+375" },
  { nombre: "Bolivia", codigoTel: "+591" },
  { nombre: "Bosnia y Herzegovina", codigoTel: "+387" },
  { nombre: "Botsuana", codigoTel: "+267" },
  { nombre: "Brasil", codigoTel: "+55" },
  { nombre: "Brunéi", codigoTel: "+673" },
  { nombre: "Bulgaria", codigoTel: "+359" },
  { nombre: "Burkina Faso", codigoTel: "+226" },
  { nombre: "Burundi", codigoTel: "+257" },
  { nombre: "Bután", codigoTel: "+975" },
  { nombre: "Cabo Verde", codigoTel: "+238" },
  { nombre: "Camboya", codigoTel: "+855" },
  { nombre: "Camerún", codigoTel: "+237" },
  { nombre: "Canadá", codigoTel: "+1" },
  { nombre: "Catar", codigoTel: "+974" },
  { nombre: "Chad", codigoTel: "+235" },
  { nombre: "Chile", codigoTel: "+56" },
  { nombre: "China", codigoTel: "+86" },
  { nombre: "Chipre", codigoTel: "+357" },
  { nombre: "Colombia", codigoTel: "+57" },
  { nombre: "Comoras", codigoTel: "+269" },
  { nombre: "Congo (Rep. Democrática)", codigoTel: "+243" },
  { nombre: "Congo (República)", codigoTel: "+242" },
  { nombre: "Corea del Norte", codigoTel: "+850" },
  { nombre: "Corea del Sur", codigoTel: "+82" },
  { nombre: "Costa de Marfil", codigoTel: "+225" },
  { nombre: "Costa Rica", codigoTel: "+506" },
  { nombre: "Croacia", codigoTel: "+385" },
  { nombre: "Cuba", codigoTel: "+53" },
  { nombre: "Dinamarca", codigoTel: "+45" },
  { nombre: "Dominica", codigoTel: "+1-767" },
  { nombre: "Ecuador", codigoTel: "+593" },
  { nombre: "Egipto", codigoTel: "+20" },
  { nombre: "El Salvador", codigoTel: "+503" },
  { nombre: "Emiratos Árabes Unidos", codigoTel: "+971" },
  { nombre: "Eritrea", codigoTel: "+291" },
  { nombre: "Eslovaquia", codigoTel: "+421" },
  { nombre: "Eslovenia", codigoTel: "+386" },
  { nombre: "España", codigoTel: "+34" },
  { nombre: "Estados Unidos", codigoTel: "+1" },
  { nombre: "Estonia", codigoTel: "+372" },
  { nombre: "Etiopía", codigoTel: "+251" },
  { nombre: "Filipinas", codigoTel: "+63" },
  { nombre: "Finlandia", codigoTel: "+358" },
  { nombre: "Fiyi", codigoTel: "+679" },
  { nombre: "Francia", codigoTel: "+33" },
  { nombre: "Gabón", codigoTel: "+241" },
  { nombre: "Gambia", codigoTel: "+220" },
  { nombre: "Georgia", codigoTel: "+995" },
  { nombre: "Ghana", codigoTel: "+233" },
  { nombre: "Granada", codigoTel: "+1-473" },
  { nombre: "Grecia", codigoTel: "+30" },
  { nombre: "Guatemala", codigoTel: "+502" },
  { nombre: "Guinea", codigoTel: "+224" },
  { nombre: "Guinea Ecuatorial", codigoTel: "+240" },
  { nombre: "Guinea-Bisáu", codigoTel: "+245" },
  { nombre: "Guyana", codigoTel: "+592" },
  { nombre: "Haití", codigoTel: "+509" },
  { nombre: "Honduras", codigoTel: "+504" },
  { nombre: "Hungría", codigoTel: "+36" },
  { nombre: "India", codigoTel: "+91" },
  { nombre: "Indonesia", codigoTel: "+62" },
  { nombre: "Irak", codigoTel: "+964" },
  { nombre: "Irán", codigoTel: "+98" },
  { nombre: "Irlanda", codigoTel: "+353" },
  { nombre: "Islandia", codigoTel: "+354" },
  { nombre: "Islas Marshall", codigoTel: "+692" },
  { nombre: "Islas Salomón", codigoTel: "+677" },
  { nombre: "Israel", codigoTel: "+972" },
  { nombre: "Italia", codigoTel: "+39" },
  { nombre: "Jamaica", codigoTel: "+1-876" },
  { nombre: "Japón", codigoTel: "+81" },
  { nombre: "Jordania", codigoTel: "+962" },
  { nombre: "Kazajistán", codigoTel: "+7" },
  { nombre: "Kenia", codigoTel: "+254" },
  { nombre: "Kirguistán", codigoTel: "+996" },
  { nombre: "Kiribati", codigoTel: "+686" },
  { nombre: "Kuwait", codigoTel: "+965" },
  { nombre: "Laos", codigoTel: "+856" },
  { nombre: "Lesoto", codigoTel: "+266" },
  { nombre: "Letonia", codigoTel: "+371" },
  { nombre: "Líbano", codigoTel: "+961" },
  { nombre: "Liberia", codigoTel: "+231" },
  { nombre: "Libia", codigoTel: "+218" },
  { nombre: "Liechtenstein", codigoTel: "+423" },
  { nombre: "Lituania", codigoTel: "+370" },
  { nombre: "Luxemburgo", codigoTel: "+352" },
  { nombre: "Madagascar", codigoTel: "+261" },
  { nombre: "Malasia", codigoTel: "+60" },
  { nombre: "Malaui", codigoTel: "+265" },
  { nombre: "Maldivas", codigoTel: "+960" },
  { nombre: "Malí", codigoTel: "+223" },
  { nombre: "Malta", codigoTel: "+356" },
  { nombre: "Marruecos", codigoTel: "+212" },
  { nombre: "Mauricio", codigoTel: "+230" },
  { nombre: "Mauritania", codigoTel: "+222" },
  { nombre: "México", codigoTel: "+52" },
  { nombre: "Micronesia", codigoTel: "+691" },
  { nombre: "Moldavia", codigoTel: "+373" },
  { nombre: "Mónaco", codigoTel: "+377" },
  { nombre: "Mongolia", codigoTel: "+976" },
  { nombre: "Montenegro", codigoTel: "+382" },
  { nombre: "Mozambique", codigoTel: "+258" },
  { nombre: "Myanmar (Birmania)", codigoTel: "+95" },
  { nombre: "Namibia", codigoTel: "+264" },
  { nombre: "Nauru", codigoTel: "+674" },
  { nombre: "Nepal", codigoTel: "+977" },
  { nombre: "Nicaragua", codigoTel: "+505" },
  { nombre: "Níger", codigoTel: "+227" },
  { nombre: "Nigeria", codigoTel: "+234" },
  { nombre: "Noruega", codigoTel: "+47" },
  { nombre: "Nueva Zelanda", codigoTel: "+64" },
  { nombre: "Omán", codigoTel: "+968" },
  { nombre: "Países Bajos", codigoTel: "+31" },
  { nombre: "Pakistán", codigoTel: "+92" },
  { nombre: "Palaos", codigoTel: "+680" },
  { nombre: "Panamá", codigoTel: "+507" },
  { nombre: "Papúa Nueva Guinea", codigoTel: "+675" },
  { nombre: "Paraguay", codigoTel: "+595" },
  { nombre: "Perú", codigoTel: "+51" },
  { nombre: "Polonia", codigoTel: "+48" },
  { nombre: "Portugal", codigoTel: "+351" },
  { nombre: "Puerto Rico", codigoTel: "+1-787" },
  { nombre: "Reino Unido", codigoTel: "+44" },
  { nombre: "República Centroafricana", codigoTel: "+236" },
  { nombre: "República Checa", codigoTel: "+420" },
  { nombre: "República Dominicana", codigoTel: "+1-809" },
  { nombre: "Ruanda", codigoTel: "+250" },
  { nombre: "Rumania", codigoTel: "+40" },
  { nombre: "Rusia", codigoTel: "+7" },
  { nombre: "Samoa", codigoTel: "+685" },
  { nombre: "San Cristóbal y Nieves", codigoTel: "+1-869" },
  { nombre: "San Marino", codigoTel: "+378" },
  { nombre: "San Vicente y las Granadinas", codigoTel: "+1-784" },
  { nombre: "Santa Lucía", codigoTel: "+1-758" },
  { nombre: "Santo Tomé y Príncipe", codigoTel: "+239" },
  { nombre: "Senegal", codigoTel: "+221" },
  { nombre: "Serbia", codigoTel: "+381" },
  { nombre: "Seychelles", codigoTel: "+248" },
  { nombre: "Sierra Leona", codigoTel: "+232" },
  { nombre: "Singapur", codigoTel: "+65" },
  { nombre: "Siria", codigoTel: "+963" },
  { nombre: "Somalia", codigoTel: "+252" },
  { nombre: "Sri Lanka", codigoTel: "+94" },
  { nombre: "Suazilandia (Esuatini)", codigoTel: "+268" },
  { nombre: "Sudáfrica", codigoTel: "+27" },
  { nombre: "Sudán", codigoTel: "+249" },
  { nombre: "Sudán del Sur", codigoTel: "+211" },
  { nombre: "Suecia", codigoTel: "+46" },
  { nombre: "Suiza", codigoTel: "+41" },
  { nombre: "Surinam", codigoTel: "+597" },
  { nombre: "Tailandia", codigoTel: "+66" },
  { nombre: "Tanzania", codigoTel: "+255" },
  { nombre: "Tayikistán", codigoTel: "+992" },
  { nombre: "Timor Oriental", codigoTel: "+670" },
  { nombre: "Togo", codigoTel: "+228" },
  { nombre: "Tonga", codigoTel: "+676" },
  { nombre: "Trinidad y Tobago", codigoTel: "+1-868" },
  { nombre: "Túnez", codigoTel: "+216" },
  { nombre: "Turkmenistán", codigoTel: "+993" },
  { nombre: "Turquía", codigoTel: "+90" },
  { nombre: "Tuvalu", codigoTel: "+688" },
  { nombre: "Ucrania", codigoTel: "+380" },
  { nombre: "Uganda", codigoTel: "+256" },
  { nombre: "Uruguay", codigoTel: "+598" },
  { nombre: "Uzbekistán", codigoTel: "+998" },
  { nombre: "Vanuatu", codigoTel: "+678" },
  { nombre: "Vaticano", codigoTel: "+379" },
  { nombre: "Venezuela", codigoTel: "+58" },
  { nombre: "Vietnam", codigoTel: "+84" },
  { nombre: "Yemen", codigoTel: "+967" },
  { nombre: "Yibuti", codigoTel: "+253" },
  { nombre: "Zambia", codigoTel: "+260" },
  { nombre: "Zimbabue", codigoTel: "+263" }
];